# TMUX config created by Copilot CLI
# Prefix
set -g prefix C-b
bind C-b send-prefix

# Mouse support and history
set -g mouse on
set -g history-limit 10000

# Index windows/panes from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi

# Status bar
set -g status on
set -g status-interval 5
set -g status-left "#[fg=green]#H"
set -g status-right "#[fg=yellow]%Y-%m-%d #[fg=cyan]%H:%M"

# Swap window left/right with { and }
bind -r '{' swap-window -t -1\; select-window -t -1
bind -r '}' swap-window -t +1\; select-window -t +1
