vim.g.mapleader = " "
vim.g.maplocalleader = " "

local opt = vim.opt
opt.number = true
opt.relativenumber = true
opt.clipboard = "unnamedplus"
opt.tabstop = 4
opt.shiftwidth = 4
opt.softtabstop = 4
opt.expandtab = true
opt.smartindent = true
opt.ignorecase = true
opt.smartcase = true
opt.termguicolors = true
opt.mouse = "a"
opt.undofile = true
opt.swapfile = false
opt.backup = false
opt.signcolumn = "yes"
opt.cursorline = true
opt.updatetime = 300
opt.timeoutlen = 500
